/*
 Generated by typeshare 1.6.0
*/

export interface AdapterResult {
	selected: string;
	adapters: string[];
}

export interface PeripheralResult {
	id: string;
	name?: string;
	connected: boolean;
}

export enum OperatingMode {
	Standby = "Standby",
	NormalHeat = "NormalHeat",
	TurboHeat = "TurboHeat",
	ExtendedHeat = "ExtendedHeat",
	Cool = "Cool",
	Dry = "Dry",
	Wait = "Wait",
}

export enum ShutDownCode {
	Normal = "Normal",
	InvalidADC = "InvalidADC",
	ThermistorTrackingError = "ThermistorTrackingError",
	FastOverTempTrip = "FastOverTempTrip",
	SlowOverTempTrip = "SlowOverTempTrip",
	FanFailure = "FanFailure",
	HeaterPowerStandby = "HeaterPowerStandby",
	ExtenderThermalTrip = "ExtenderThermalTrip",
}

export enum UpdateStatus {
	Idle = "Idle",
	Starting = "Starting",
	ConnectingToAP = "ConnectingToAP",
	GotIPAddress = "GotIPAddress",
	CheckingConnection = "CheckingConnection",
	CheckingForUpdate = "CheckingForUpdate",
	Updating = "Updating",
	RestartingBedJet = "RestartingBedJet",
	NoWiFiConfig = "NoWiFiConfig",
	UnableToConnect = "UnableToConnect",
	DHCPFailure = "DHCPFailure",
	UnableToContactServer = "UnableToContactServer",
	ConnectionTestOK = "ConnectionTestOK",
	ConnectionTestFailed = "ConnectionTestFailed",
	NoUpdateNeeded = "NoUpdateNeeded",
	RadioDisabled = "RadioDisabled",
	RestartingBedJetTerminal = "RestartingBedJetTerminal",
	UpdateFailed = "UpdateFailed",
}

export interface DeviceStatus {
	/** The total runtime left on the device */
	remaining_hours: number;
	remaining_minutes: number;
	remaining_seconds: number;
	/** Stored in units of 0.5 degrees celsius */
	actual_temp: number;
	/** Stored in units of 0.5 degrees celsius */
	target_temp: number;
	operating_mode: OperatingMode;
	/** Represented as a number between 0-19 */
	fan_step: number;
	/** Maximum runtime for the current mode */
	max_duration_hours: number;
	max_duration_minutes: number;
	/** Stored in units of 0.5 degrees celsius */
	min_target_temp: number;
	/** Stored in units of 0.5 degrees celsius */
	max_target_temp: number;
	/** Stored in units of 0.5 degrees celsius */
	ambient_temp: number;
	shutdown_code: ShutDownCode;
	update_status: UpdateStatus;
}

export interface ParsedDeviceStatus {
	remaining_duration: number;
	/** As degrees C */
	actual_temp: number;
	/** As degreesC */
	target_temp: number;
	operating_mode: OperatingMode;
	/** As a percent 0 - 100 */
	fan_step: number;
	max_duration: number;
	min_target_temp: number;
	max_target_temp: number;
	ambient_temp: number;
	shutdown_code: ShutDownCode;
	update_status: UpdateStatus;
}

export interface DeviceStatusEvent {
	id: string;
	status: DeviceStatus;
}

export enum ButtonCode {
	Stop = "Stop",
	Cool = "Cool",
	Heat = "Heat",
	Turbo = "Turbo",
	Dry = "Dry",
	ExternalHeat = "ExternalHeat",
	FanUp = "FanUp",
	FanDown = "FanDown",
	TempUp1C = "TempUp1C",
	TempDown1C = "TempDown1C",
	TempUp1F = "TempUp1F",
	TempDown1F = "TempDown1F",
	Memory1Recall = "Memory1Recall",
	Memory2Recall = "Memory2Recall",
	Memory3Recall = "Memory3Recall",
	Memory1Store = "Memory1Store",
	Memory2Store = "Memory2Store",
	Memory3Store = "Memory3Store",
	StartConnectionTest = "StartConnectionTest",
	StartFirmwareUpdate = "StartFirmwareUpdate",
	SetLowPowerMode = "SetLowPowerMode",
	SetNormalPowerMode = "SetNormalPowerMode",
	EnableRingOfLight = "EnableRingOfLight",
	DisableRingOfLight = "DisableRingOfLight",
	MuteBeeper = "MuteBeeper",
	UnmuteBeeper = "UnmuteBeeper",
	ResetToFactorySettings = "ResetToFactorySettings",
	EnableWiFiBT = "EnableWiFiBT",
	DisableWiFiBT = "DisableWiFiBT",
	SetConfigCompleteFlag = "SetConfigCompleteFlag",
}

export enum CommandClass {
	Button = "Button",
	SetTime = "SetTime",
	SetTemp = "SetTemp",
	SetFan = "SetFan",
	SetClock = "SetClock",
	SetParameter = "SetParameter",
}

export type TempParam = 
	/** The temperature in degrees Celsius */
	| { type: "Celsius", value: number }
	/** The temperature in degrees Fahrenheit */
	| { type: "Fahrenheit", value: number };

export type FanParam = 
	| { type: "Step", value: number }
	| { type: "Percent", value: number };

/** A higher level enum containing the commands that can be sent to the device, and the parameters to those commands */
export type Command = 
	| { type: "Button", content: ButtonCode }
	| { type: "SetTime", content: {
	hours: number;
	minutes: number;
}}
	| { type: "SetTemp", content: TempParam }
	| { type: "SetFan", content: FanParam }
	| { type: "SetClock", content: {
	hours: number;
	minutes: number;
}}
	| { type: "SetParam", content: SetParamKind };

export type SetParamKind = 
	/** Cannot contain a String longer than 15 bytes. */
	| { type: "DeviceName", value: string };

